# Generated by Django 4.2.6 on 2023-11-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
