# Generated by Django 4.2.6 on 2023-11-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_delete_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(default='text', max_length=10),
        ),
    ]
