# Generated by Django 4.2.6 on 2023-11-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
