# Generated by Django 4.2.6 on 2023-11-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatmessage_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_data',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
