# Generated by Django 4.2.6 on 2023-11-09 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_chatmessage_uploaded_chatmessage_file_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_data',
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatmessage')),
            ],
        ),
    ]
